%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'endogenous_growth_sticky';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('endogenous_growth_sticky.log');
M_.exo_names = 'epsilon_chi';
M_.exo_names_tex = '{\epsilon}^{\chi}';
M_.exo_names_long = 'epsilon_chi';
M_.endo_names = 'g';
M_.endo_names_tex = '{g}';
M_.endo_names_long = 'Growth';
M_.endo_names = char(M_.endo_names, 'ZD');
M_.endo_names_tex = char(M_.endo_names_tex, '{Z_D}');
M_.endo_names_long = char(M_.endo_names_long, 'ZD');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, '{\lambda}');
M_.endo_names_long = char(M_.endo_names_long, 'lambda');
M_.endo_names = char(M_.endo_names, 'VD');
M_.endo_names_tex = char(M_.endo_names_tex, '{V_D}');
M_.endo_names_long = char(M_.endo_names_long, 'VD');
M_.endo_names = char(M_.endo_names, 'M');
M_.endo_names_tex = char(M_.endo_names_tex, '{M}');
M_.endo_names_long = char(M_.endo_names_long, 'M');
M_.endo_names = char(M_.endo_names, 'J');
M_.endo_names_tex = char(M_.endo_names_tex, '{J}');
M_.endo_names_long = char(M_.endo_names_long, 'J');
M_.endo_names = char(M_.endo_names, 'H');
M_.endo_names_tex = char(M_.endo_names_tex, '{H}');
M_.endo_names_long = char(M_.endo_names_long, 'H');
M_.endo_names = char(M_.endo_names, 'Pi');
M_.endo_names_tex = char(M_.endo_names_tex, '{\Pi}');
M_.endo_names_long = char(M_.endo_names_long, 'Pi');
M_.endo_names = char(M_.endo_names, 'ND');
M_.endo_names_tex = char(M_.endo_names_tex, '{N_D}');
M_.endo_names_long = char(M_.endo_names_long, 'ND');
M_.endo_names = char(M_.endo_names, 'YDW');
M_.endo_names_tex = char(M_.endo_names_tex, '{Y^W_D}');
M_.endo_names_long = char(M_.endo_names_long, 'YDW');
M_.endo_names = char(M_.endo_names, 'YD');
M_.endo_names_tex = char(M_.endo_names_tex, '{Y_D}');
M_.endo_names_long = char(M_.endo_names_long, 'YD');
M_.endo_names = char(M_.endo_names, 'CD');
M_.endo_names_tex = char(M_.endo_names_tex, '{C_D}');
M_.endo_names_long = char(M_.endo_names_long, 'CD');
M_.endo_names = char(M_.endo_names, 'Lambda');
M_.endo_names_tex = char(M_.endo_names_tex, '{\Lambda}');
M_.endo_names_long = char(M_.endo_names_long, 'Lambda');
M_.endo_names = char(M_.endo_names, 'UCD');
M_.endo_names_tex = char(M_.endo_names_tex, '{U_{CD}}');
M_.endo_names_long = char(M_.endo_names_long, 'UCD');
M_.endo_names = char(M_.endo_names, 'muD');
M_.endo_names_tex = char(M_.endo_names_tex, '{{\mu}_{D}}');
M_.endo_names_long = char(M_.endo_names_long, 'muD');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, '{L}');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'GammaD');
M_.endo_names_tex = char(M_.endo_names_tex, '{\Gamma_D}');
M_.endo_names_long = char(M_.endo_names_long, 'GammaD');
M_.endo_names = char(M_.endo_names, 'KD');
M_.endo_names_tex = char(M_.endo_names_tex, '{K_D}');
M_.endo_names_long = char(M_.endo_names_long, 'KD');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, '{Q}');
M_.endo_names_long = char(M_.endo_names_long, 'Q');
M_.endo_names = char(M_.endo_names, 'ID');
M_.endo_names_tex = char(M_.endo_names_tex, '{I_D}');
M_.endo_names_long = char(M_.endo_names_long, 'ID');
M_.endo_names = char(M_.endo_names, 'zeta');
M_.endo_names_tex = char(M_.endo_names_tex, '{\zeta}');
M_.endo_names_long = char(M_.endo_names_long, 'zeta');
M_.endo_names = char(M_.endo_names, 'SD');
M_.endo_names_tex = char(M_.endo_names_tex, '{\mathcal{S}_{D}}');
M_.endo_names_long = char(M_.endo_names_long, 'SD');
M_.endo_names = char(M_.endo_names, 'XD');
M_.endo_names_tex = char(M_.endo_names_tex, '{X_D}');
M_.endo_names_long = char(M_.endo_names_long, 'XD');
M_.endo_names = char(M_.endo_names, 'RD');
M_.endo_names_tex = char(M_.endo_names_tex, '{\mathcal{R}_{D}}');
M_.endo_names_long = char(M_.endo_names_long, 'RD');
M_.endo_names = char(M_.endo_names, 'mkup');
M_.endo_names_tex = char(M_.endo_names_tex, '\mathcal{M}');
M_.endo_names_long = char(M_.endo_names_long, 'mkup');
M_.endo_names = char(M_.endo_names, 'pi');
M_.endo_names_tex = char(M_.endo_names_tex, '{\pi}');
M_.endo_names_long = char(M_.endo_names_long, 'pi');
M_.endo_names = char(M_.endo_names, 'pi_star');
M_.endo_names_tex = char(M_.endo_names_tex, '{\pi^*}');
M_.endo_names_long = char(M_.endo_names_long, 'pi_star');
M_.endo_names = char(M_.endo_names, 'x1D');
M_.endo_names_tex = char(M_.endo_names_tex, '{x_{1D}}');
M_.endo_names_long = char(M_.endo_names_long, 'x1D');
M_.endo_names = char(M_.endo_names, 'x2D');
M_.endo_names_tex = char(M_.endo_names_tex, '{x_{2D}}');
M_.endo_names_long = char(M_.endo_names_long, 'x2D');
M_.endo_names = char(M_.endo_names, 'R_nom');
M_.endo_names_tex = char(M_.endo_names_tex, '{R}');
M_.endo_names_long = char(M_.endo_names_long, 'R_nom');
M_.endo_names = char(M_.endo_names, 'f_fcn');
M_.endo_names_tex = char(M_.endo_names_tex, '{\left.       f\left( \cdot \right)            \right|}');
M_.endo_names_long = char(M_.endo_names_long, 'f_fcn');
M_.endo_names = char(M_.endo_names, 'f_fcn_prime');
M_.endo_names_tex = char(M_.endo_names_tex, '{\left.       f^‎{\prime}\left( \cdot \right)   \right|}');
M_.endo_names_long = char(M_.endo_names_long, 'f_fcn_prime');
M_.endo_names = char(M_.endo_names, 'g_fcn');
M_.endo_names_tex = char(M_.endo_names_tex, '{\left.       g\left( \cdot \right)            \right|}');
M_.endo_names_long = char(M_.endo_names_long, 'g_fcn');
M_.endo_names = char(M_.endo_names, 'g_fcn_prime');
M_.endo_names_tex = char(M_.endo_names_tex, '{\left.       g^‎{\prime}\left( \cdot \right)   \right|}');
M_.endo_names_long = char(M_.endo_names_long, 'g_fcn_prime');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_20_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_20\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_20_1');
M_.param_names = 'beta';
M_.param_names_tex = '\beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, '\alpha');
M_.param_names_long = char(M_.param_names_long, 'alpha');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, '\epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'rho');
M_.param_names_tex = char(M_.param_names_tex, '\rho');
M_.param_names_long = char(M_.param_names_long, 'rho');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, '\delta');
M_.param_names_long = char(M_.param_names_long, 'delta');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, '\chi');
M_.param_names_long = char(M_.param_names_long, 'chi');
M_.param_names = char(M_.param_names, 'vartheta');
M_.param_names_tex = char(M_.param_names_tex, '\vartheta');
M_.param_names_long = char(M_.param_names_long, 'vartheta');
M_.param_names = char(M_.param_names, 'gamma');
M_.param_names_tex = char(M_.param_names_tex, '\gamma');
M_.param_names_long = char(M_.param_names_long, 'gamma');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, '\phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, '\eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'rhozeta');
M_.param_names_tex = char(M_.param_names_tex, '{\rho}_{\zeta}');
M_.param_names_long = char(M_.param_names_long, 'rhozeta');
M_.param_names = char(M_.param_names, 'rhozeta2');
M_.param_names_tex = char(M_.param_names_tex, '{\rho}_{\zeta2}');
M_.param_names_long = char(M_.param_names_long, 'rhozeta2');
M_.param_names = char(M_.param_names, 'sigmazeta');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma}_{\zeta}');
M_.param_names_long = char(M_.param_names_long, 'sigmazeta');
M_.param_names = char(M_.param_names, 'zetabar');
M_.param_names_tex = char(M_.param_names_tex, '\overline{\zeta}');
M_.param_names_long = char(M_.param_names_long, 'zetabar');
M_.param_names = char(M_.param_names, 'mkup_ss');
M_.param_names_tex = char(M_.param_names_tex, '{\mathcal{M}^{ss}}');
M_.param_names_long = char(M_.param_names_long, 'mkup_ss');
M_.param_names = char(M_.param_names, 'psi_N');
M_.param_names_tex = char(M_.param_names_tex, '\psi_N');
M_.param_names_long = char(M_.param_names_long, 'psi_N');
M_.param_names = char(M_.param_names, 'psi_I');
M_.param_names_tex = char(M_.param_names_tex, '\psi_I');
M_.param_names_long = char(M_.param_names_long, 'psi_I');
M_.param_names = char(M_.param_names, 'gg');
M_.param_names_tex = char(M_.param_names_tex, 'g^{BGP}');
M_.param_names_long = char(M_.param_names_long, 'gg');
M_.param_names = char(M_.param_names, 'R_nom_ss');
M_.param_names_tex = char(M_.param_names_tex, '{R^{ss}}');
M_.param_names_long = char(M_.param_names_long, 'R_nom_ss');
M_.param_names = char(M_.param_names, 'gamma_pi');
M_.param_names_tex = char(M_.param_names_tex, '{{\gamma}_{\pi}}');
M_.param_names_long = char(M_.param_names_long, 'gamma_pi');
M_.param_names = char(M_.param_names, 'gamma_y');
M_.param_names_tex = char(M_.param_names_tex, '{{\gamma}_{y}}');
M_.param_names_long = char(M_.param_names_long, 'gamma_y');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, '{\omega}');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, '{\theta}');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'lambda_bar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\lambda}}');
M_.param_names_long = char(M_.param_names_long, 'lambda_bar');
M_.param_names = char(M_.param_names, 'rho_lambda');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_\lambda}');
M_.param_names_long = char(M_.param_names_long, 'rho_lambda');
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 35;
M_.param_nbr = 25;
M_.orig_endo_nbr = 34;
M_.aux_vars(1).endo_index = 35;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 21;
M_.aux_vars(1).orig_lead_lag = -1;
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('endogenous_growth_sticky_static');
erase_compiled_function('endogenous_growth_sticky_dynamic');
M_.lead_lag_incidence = [
 1 11 0;
 2 12 0;
 0 13 0;
 3 14 46;
 0 15 0;
 0 16 47;
 0 17 48;
 0 18 0;
 4 19 49;
 0 20 50;
 0 21 0;
 0 22 51;
 0 23 52;
 5 24 0;
 0 25 53;
 0 26 0;
 6 27 0;
 7 28 0;
 0 29 54;
 8 30 55;
 9 31 0;
 0 32 0;
 0 33 56;
 0 34 0;
 0 35 0;
 0 36 57;
 0 37 0;
 0 38 58;
 0 39 59;
 0 40 0;
 0 41 0;
 0 42 60;
 0 43 0;
 0 44 61;
 10 45 0;]';
M_.nstatic = 12;
M_.nfwrd   = 13;
M_.npred   = 7;
M_.nboth   = 3;
M_.nsfwrd   = 16;
M_.nspred   = 10;
M_.ndynamic   = 23;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(35, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(25, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 171;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
close all;
do_estimate = 1; 
M_.params( 1 ) = 0.96;
beta = M_.params( 1 );
M_.params( 2 ) = 0.33;
alpha = M_.params( 2 );
M_.params( 3 ) = 0.5;
epsilon = M_.params( 3 );
M_.params( 4 ) = 1;
rho = M_.params( 4 );
M_.params( 5 ) = 0.10;
delta = M_.params( 5 );
M_.params( 6 ) = 1.5652;
chi = M_.params( 6 );
M_.params( 7 ) = 1+1/(1-M_.params(2));
vartheta = M_.params( 7 );
M_.params( 10 ) = 0.3;
eta = M_.params( 10 );
M_.params( 8 ) = 0.5;
gamma = M_.params( 8 );
M_.params( 9 ) = 0.95;
phi = M_.params( 9 );
M_.params( 11 ) = 0.4;
rhozeta = M_.params( 11 );
M_.params( 12 ) = 0.0004;
rhozeta2 = M_.params( 12 );
M_.params( 13 ) = 0.5;
sigmazeta = M_.params( 13 );
M_.params( 14 ) = 0.6;
zetabar = M_.params( 14 );
M_.params( 20 ) = 1.5;
gamma_pi = M_.params( 20 );
M_.params( 21 ) = 0.1;
gamma_y = M_.params( 21 );
M_.params( 23 ) = 1;
theta = M_.params( 23 );
M_.params( 22 ) = 4.167;
omega = M_.params( 22 );
M_.params( 15 ) = M_.params(22)/(M_.params(22)-1);
mkup_ss = M_.params( 15 );
M_.params( 16 ) = 10;
psi_N = M_.params( 16 );
M_.params( 17 ) = 1;
psi_I = M_.params( 17 );
M_.params( 24 ) = 1.5;
lambda_bar = M_.params( 24 );
M_.params( 25 ) = 0.7;
rho_lambda = M_.params( 25 );
M_.params( 10 ) = 0.6331;
eta = M_.params( 10 );
M_.params( 8 ) = 0.9769;
gamma = M_.params( 8 );
M_.params( 9 ) = 0.9890;
phi = M_.params( 9 );
M_.params( 24 ) = 0.3;
lambda_bar = M_.params( 24 );
M_.params( 16 ) = 20;
psi_N = M_.params( 16 );
M_.params( 11 ) = 0.6557;
rhozeta = M_.params( 11 );
M_.params( 12 ) = 0.0004;
rhozeta2 = M_.params( 12 );
M_.params( 13 ) = 0.9087;
sigmazeta = M_.params( 13 );
M_.params( 25 ) = 0.7905;
rho_lambda = M_.params( 25 );
M_.params( 10 ) = 0.09999;
eta = M_.params( 10 );
M_.params( 8 ) = 0.899911;
gamma = M_.params( 8 );
M_.params( 9 ) = 0.941;
phi = M_.params( 9 );
M_.params( 24 ) = 1.0045;
lambda_bar = M_.params( 24 );
M_.params( 16 ) = 10;
psi_N = M_.params( 16 );
M_.params( 11 ) = 0.15009;
rhozeta = M_.params( 11 );
M_.params( 13 ) = 1.45;
sigmazeta = M_.params( 13 );
M_.params( 25 ) = 0.892;
rho_lambda = M_.params( 25 );
M_.params( 10 ) = 0.05170475943;
eta = M_.params( 10 );
M_.params( 8 ) = 0.9893840947;
gamma = M_.params( 8 );
M_.params( 9 ) = 0.9898787385;
phi = M_.params( 9 );
M_.params( 24 ) = 0.1053043122;
lambda_bar = M_.params( 24 );
M_.params( 16 ) = 10.1111927;
psi_N = M_.params( 16 );
M_.params( 11 ) = 0.836779638;
rhozeta = M_.params( 11 );
M_.params( 12 ) = 0.0003359981795;
rhozeta2 = M_.params( 12 );
M_.params( 13 ) = 0.4911254073;
sigmazeta = M_.params( 13 );
M_.params( 25 ) = 0.8050435049;
rho_lambda = M_.params( 25 );
global pvarcoirfs_clean;
load 'pvar_coirfs_full';
pvarcoirfs_clean = pvarcoirfs;
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (1)^2;
COUNT.total = 0;
COUNT.ss_found = 0;
COUNT.ss_notfound = 0;
COUNT.ss_neg = 0;
set_dynare_seed(092677);
evalin('base','save level0workspace oo_ M_ options_')
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 11;
options_.loglinear = 1;
options_.nocorr = 1;
options_.nodisplay = 1;
options_.nograph = 1;
options_.nomoments = 1;
options_.order = 1;
options_.periods = 600;
var_list_=[];
info = stoch_simul(var_list_);
post_processing_irfs;                                                       
plot_var_irfs;                                                              
post_processing_irfs_plot;                                                  
post_processing_irfs_distance;                                              
if do_estimate == 0;
return;
elseif do_estimate == 1
x_start=[eta, gamma, phi, lambda_bar, psi_N, rhozeta, rhozeta2, sigmazeta, rho_lambda]; 
x_start_unbounded = boundsINV(x_start);
H0 = 1e-2*eye(length(x_start)); 
H0 = 1e-1*eye(length(x_start)); 
crit = 1e-7; 
nit = 1000; 
nit = 800;
nit = 200;
options_.nocorr=1;
options_.noprint=1;
options_.verbosity=0;
[fhat, params_unbounded] = csminwel(@distance_fcn     ,x_start_unbounded,H0,[],crit,nit);
fhat
elseif do_estimate == 2
x_start=[eta, gamma, phi, lambda_bar, psi_N, rhozeta, rhozeta2, sigmazeta, rho_lambda]; 
x_start_unbounded = boundsINV(x_start);
opts = psoptimset('Display','diagnose'); 
[params_unbounded, FVAL,EXITFLAG] = patternsearch(@distance_fcn, x_start_unbounded,[],[],[],[],[],[],[],opts)
end
if do_estimate > 0
[ params ] = bounds( params_unbounded );
set_param_value('eta', params(1) );
set_param_value('gamma', params(2) );
set_param_value('phi', params(3) );
set_param_value('lambda_bar', params(4) );
set_param_value('psi_N', params(5) );
set_param_value('rhozeta', params(6) );
set_param_value('rhozeta2', params(7) );
set_param_value('sigmazeta', params(8) );
set_param_value('rho_lambda', params(9) );
oo_.irfs = {}; 
steady;
var_list_=[];
info = stoch_simul(var_list_);                                              
post_processing_irfs;                                                       
post_processing_irfs_plot;                                                  
axis tight;
legend('initial','var', 'b', 'b', 'final');
disp('[eta, gamma, phi, lambda_bar, psi_N, rhozeta, rhozeta2, sigmazeta, zetabar]')
params
x_start
disp(sprintf('eta = %0.10g;', params(1) ));
disp(sprintf('gamma = %0.10g;', params(2) ));
disp(sprintf('phi = %0.10g;', params(3) ));
disp(sprintf('lambda_bar = %0.10g;', params(4) ));
disp(sprintf('psi_N = %0.10g;', params(5) ));
disp(sprintf('rhozeta = %0.10g;', params(6) ));
disp(sprintf('rhozeta2 = %0.10g;', params(7) ));
disp(sprintf('sigmazeta = %0.10g;', params(8) ));
disp(sprintf('rho_lambda = %0.10g;', params(9) ));
end
save('endogenous_growth_sticky_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('endogenous_growth_sticky_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('endogenous_growth_sticky_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('endogenous_growth_sticky_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('endogenous_growth_sticky_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
